FROM ubuntu:bionic
USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    cmake \
    git \
    python3-pip \
    python3-setuptools \
    python3-dev \
    python3 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    mosquitto-clients \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install cython
RUN pip3 install numpy
RUN pip3 install opencv-python
RUN pip3 install paho-mqtt
RUN pip3 install requests
 
VOLUME /containerbase
WORKDIR /containerbase

# assumes that the root is /fdfiles
COPY . /containerbase

ENTRYPOINT python3 face_detector.py
